### PR TITLE
Handles temp units localization (F/C)

### LINKED ISSUE #34: Select temperature unit based on location
The current version uses Celsius by default. We need to make this location specific.

### PR DESCRIPTION
**Pull request by iamplugged**
Closes #34 

image

### CODE REVIEW

**Review by vpetersson — CHANGES_REQUESTED** [review]
No, this looks wrong. You never put the degree sign like that. It needs to be on the top. I'm also inclined to simply not show the F or C at all.

**Comment by iamplugged** [comment]
> No, this looks wrong. You never put the degree sign like that. It needs to be on the top. I'm also inclined to simply not show the F or C at all.

@L4cko Do we just remove it?

**Comment by L4cko** [comment]
@vpetersson @iamplugged 
image
I'm ok with F and C. It's small and not that visible.

**Comment by vpetersson** [comment]
> @vpetersson @iamplugged image I'm ok with F and C. It's small and not that visible.

Yeah I'm fine with that look.

**Review by vpetersson — APPROVED** [review]

**Pull request merged**
